#!/bin/sh

# Load environment variables
default_image=${DOSH_DEFAULT_IMAGE:-debian:buster-slim}
shell=${DOSH_DEFAULT_SHELL:-bash}
init_hook=$DOSH_INIT_HOOK

# Parse parameters
if [[ $@ != -* ]]; then
  user_supplied_image=$1
  shift
fi
image=${user_supplied_image:-$default_image}
user_supplied_docker_run_params=$@

# Define init script
init_script="
  cd /workdir

  $init_hook

  if command -v $shell > /dev/null; then
    exec $shell
  else
    exec sh
  fi
"

# Run docker image
docker run \
  # Make the session interactive
  -it \
  # Mount the current working dir inside the image
  -v ${PWD}:/workdir \
  # Pass through any additional user params
  $user_supplied_docker_run_params \
  # Ensure we always start a shell
  --entrypoint sh \
  # Load the image and pass the init script to sh
  $image -c "$init_script"
