name: CI
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y shellcheck
    - run: shellcheck dosh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - run: sudo snap install shfmt
    - run: shfmt dosh
